### ISSUE TITLE
Where did the code comments go here?

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [Jemtaly/CryptoXX#1]
Is it possible to write comments to your code in English? Please.
I like your project.
Here is my project: [TDOM-EncryptOrDecryptFile-Reborn](https://github.com/Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn)

**Comment by Jemtaly** [comment]
可以，谢谢你的建议。这个项目之前只是用于个人学习，所以一直没有添加注释和使用说明之类的，后续会尽可能添加，总之感谢你的喜欢！（我也是中国人所以用中文交流也是可以的）

OK, thanks for your proposal. This project was only used for personal study at first, so I didn't think to write comments and manuals, however, I will add as much as possible in the future. Thank you for your liking!
